[package]
name = "guessing_game"
version = "0.0.1"
authors = ["Blake Kaplan <mrbkap@gmail.com>"]

[dependencies]
rand = "0.3"

[[bin]]
name = "guessing_game"
path = "src/main.rs"

[[bin]]
name = "solver"
path = "solver/main.rs"
